stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - params.yaml
    - src/data/make_dataset.py
    outs:
    - data/raw


  build_feature:
    cmd: python src/features/build_features.py
    deps:
    - data/raw
    - params.yaml
    - src/features/build_features.py
    outs:
    - data/processed
    - models/le_pkl.pkl
    # - models/ohe.pkl
    # - models/oe.pkl
    - models/trf.pkl


  model:
    cmd: python src/models/train_model.py
    deps:
    - data/processed
    - params.yaml
    - src/models/train_model.py
    outs:
    - models/model.pkl
    metrics:
    - reports/metrics.json:
        cache: false

  model_registry:
    cmd: python src/models/model_registry.py
    deps:
    - models/model.pkl
    - reports/experiment.json
    - src/models/model_registry.py