data_ingestion:
  url: https://raw.githubusercontent.com/SuyashPatil-max/uber_datasets/refs/heads/main/ncr_ride_bookings.csv


build_feature:
  test_size: 0.2
  random_state: 42


smote:
  sampling_strategy: 0.542051105432863
  k_neighbors: 10
  random_state: 42

cat_model:
  iterations: 3000
  learning_rate: 0.0011483157245435395
  depth: 10
  l2_leaf_reg: 1.120352825702718
  bagging_temperature: 6.2358405482911206
  border_count: 120
  class_weights:
    - 1
    - 5.361684247757537
  verbose: false
  loss_function: Logloss
  eval_metric: F1
  random_seed: 42


categorical_features:
    cat_features: ['Vehicle Type', 'Payment Method',
                        'TimeOfDay','Season','Quarter','IsWeekend','DayOfWeek','Pickup Location','Drop Location']
