name: CI_Pipeline 
on: 
  push: 
      branches:
        - main
  pull_request: 
      branches:
        - main

jobs: 
    proejct-testing:
      runs-on: ubuntu-latest

      steps:
        - name: code-checkout
          uses: action/checkout@v4
        
        - name: python-setup
          uses: action/setup-python@v5
          with:
              python-version: "3.13"
        
        - name: isntall dependencies
          run: |
              pip install --upgrade pip
              pip install -r requirements.txt
        
        - name: dvc pipeline
          env: 
              DAGSHUB_TOKEN: ${{secrets.DAGSHUB_TOKEN}}
          run: | 
              dvc repro