name: CI_CD_PIPELINE

on:
  push:
    branches:
      - main

# the jobs are being started in the order they are defined, but they can run in parallel if they don't have dependencies on each other.

jobs:

  project-testing:
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install-dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pip install "dvc[s3]"
          pip install dagshub

      - name: s3_config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      - name: check-dvc-environment
        run: |
          dvc version
          pip show dvc
          pip show pygtrie

      - name: pull-data-from-s3
        run: |
          dvc version
          pip show dvc
          pip show pygtrie
          dvc pull

      - name: dagshub-auth
        env:
          DAGSHUB_USER: ${{ secrets.DAGSHUB_USER }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          dagshub login --token "$DAGSHUB_TOKEN"

      - name: dvc-pipeline
        run: |
          dvc repro


  backend-testing:
    needs: project-testing
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install-dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install "dvc[s3]"

      - name: s3_config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: pull-data-from-s3
        run: |
          dvc pull

      - name: start-backend
        run: |
          python -m uvicorn backend.app:app --host 127.0.0.1 --port 8002 &
          echo $! > uvicorn.pid

      - name: stop-for-backend
        run: |
          sleep 10

      - name: health-check
        run: |
          curl --fail http://127.0.0.1:8002/health

      - name: stop-backend
        if: always()
        run: |
          kill $(cat uvicorn.pid)


  docker-image:
    needs: backend-testing
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      

      - name: install-dependencies
        run: |
            pip install --upgrade pip
            pip install dvc
            pip install dvc[s3]
            pip install "pygtrie==2.5.0"


      - name: s3_config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1


      - name: pull-data-from-s3
        run: |
          dvc pull


      - name: build-docker-image
        run: |
          docker build -t uber_image:latest .


      - name: run-docker-container
        run: |
          docker run -d -p 8002:8002 --name uber_container uber_image:latest

      - name: test-container
        run: |
          sleep 10
          curl --fail http://127.0.0.1:8002/health

      - name: delete-container-and-image
        if: always()
        run: |
          docker stop uber_container || true
          docker rm uber_container || true
          docker rmi uber_image:latest || true


  backend-ecr-push:
    needs: docker-image
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: setup-python
        uses: actions/setup-python@v5
      
      - name: install-dependencies
        run: |
            pip install --upgrade pip
            pip install dvc
            pip install dvc[s3]
            pip install "pygtrie==2.5.0"

      - name: s3_config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: pull-data-from-s3
        run: |
          dvc pull

      - name: aws_config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1


      - name: ecr-login
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 942091278141.dkr.ecr.eu-north-1.amazonaws.com

      - name: build-tag-image
        run: |
          docker build -t uber-backend .
          docker tag uber-backend:latest 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-backend:latest

      - name: push-to-ecr
        run: |
          docker push 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-backend:latest
  

  frontend-ecr-push:
    needs: docker-image
    runs-on: ubuntu-latest

    steps:

      - name: checkout-code
        uses: actions/checkout@v4


      - name: aws-config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: ecr-login
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 942091278141.dkr.ecr.eu-north-1.amazonaws.com
      
      - name: image-build-and-tag
        working-directory: frontend
        env:
          VITE_API_BASE_URL: ${{ vars.VITE_API_BASE_URL || 'http://uber-lb-1-2111498017.eu-north-1.elb.amazonaws.com' }}
        run:  |
            docker build --build-arg VITE_API_BASE_URL="$VITE_API_BASE_URL" -t uber-frontend .
            docker tag uber-frontend:latest 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-frontend:latest

      - name: push-to-ecr
        run: |
          docker push 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-frontend:latest

      
  ec2-deployment-backend:
    needs:
      - backend-ecr-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 on backend
        uses: appleboy/ssh-action@v1.2.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        with:
          host: ${{ secrets.EC2_HOST_BACKEND }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION
          script: |
            set -e

            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION

            sudo apt-get update -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get install -y docker.io
            fi


            sudo systemctl enable docker
            sudo systemctl start docker

            if ! command -v aws >/dev/null 2>&1; then
              sudo apt-get install -y unzip curl
              curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -q -o awscliv2.zip
              sudo ./aws/install --update
              rm -rf awscliv2.zip aws
            fi

            sudo docker stop uber-backend 2>/dev/null || true
            sudo docker rm uber-backend 2>/dev/null || true
            sudo docker rmi 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-backend:latest 2>/dev/null || true
            aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin 942091278141.dkr.ecr.eu-north-1.amazonaws.com
            sudo docker pull 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-backend:latest
            sudo docker run -d --name uber-backend -p 8002:8002 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-backend:latest
            sudo docker ps


  ec2-deployment-frontend:
    needs:
      - frontend-ecr-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 on frontend
        uses: appleboy/ssh-action@v1.2.2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ECR_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ECR_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-north-1
        with:
          host: ${{ secrets.EC2_HOST_FRONTEND}}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_DEFAULT_REGION
          script: |
            set -e

            export AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY AWS_DEFAULT_REGION

            sudo apt-get update -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get upgrade -y

            if ! command -v docker >/dev/null 2>&1; then
              sudo apt-get install -y docker.io
            fi

            sudo systemctl enable docker
            sudo systemctl start docker

            if ! command -v aws >/dev/null 2>&1; then
              sudo apt-get install -y unzip curl
              curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
              unzip -q -o awscliv2.zip
              sudo ./aws/install --update
              rm -rf awscliv2.zip aws
            fi

            sudo docker stop uber-frontend 2>/dev/null || true
            sudo docker rm uber-frontend 2>/dev/null || true
            sudo docker rmi 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-frontend:latest 2>/dev/null || true
            aws ecr get-login-password --region eu-north-1 | sudo docker login --username AWS --password-stdin 942091278141.dkr.ecr.eu-north-1.amazonaws.com
            sudo docker pull 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-frontend:latest
            sudo docker run -d --name uber-frontend -p 5174:80 942091278141.dkr.ecr.eu-north-1.amazonaws.com/uber-frontend:latest
            sudo docker ps